# Generated by Django 2.1.15 on 2021-05-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210520_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilades',
            new_name='Habilidades',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
