# Generated by Django 2.1.15 on 2021-05-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='fecha',
        ),
    ]
