# Generated by Django 2.1.15 on 2021-05-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_remove_departamento_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de Empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'shor_name')},
        ),
    ]
